---
title: "Top Tens"
author: "Yu"
date: "3/8/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
rm(list=ls())
require(dplyr)
knitr::opts_knit$set(root.dir = "~/Git/violation-data-analysis")
```

## R Markdown

```{r top 10 based on num.death}
load("./San Antonio/output/result.RData")
complete.active.quarters %>% arrange(desc(num.death)) %>% select(mine_id, mine.name, year, quarter, num.death) %>% head(10)
```

```{r top 10 based on certain mine}
complete.active.quarters %>% filter(mine_id == 101322) %>% select(mine.name, year, quarter, last.year.lost) %>% head(10)
```

```{r simple lm}
load("./San Antonio/output/result.RData")
summary(lm(1*num.death+0*num.days.lost+0*num.days.restrict~last.quarter.lost+last.year.lost+last.three.years.lost
           +last.quarter.restrict+last.year.restrict+last.three.years.restrict
           +last.quarter.viol+last.year.viol+last.three.years.viol
           +last.quarter.death+last.year.death+last.three.years.death, 
           data=complete.active.quarters %>% filter(active)))

summary(lm(num.death~last.three.years.lost+last.quarter.viol+last.year.viol, data=complete.active.quarters %>% filter(active)))
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
